/**
 * CatalogoWS_PortType.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos;

public interface CatalogoWS_PortType extends java.rmi.Remote {
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.PerfilTO registrarPerfil(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.PerfilTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void actualizarPerfil(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.PerfilTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void eliminarPerfil(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.PerfilTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaPerfilTO consultarPerfiles(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosPerfilTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoServicioTO[] consultarServiciosBanco(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosTipoServicioTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoServicioTO registrarTipoServicio(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoServicioTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void actualizarTipoServicio(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoServicioTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void eliminarTipoServicio(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoServicioTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoValorTO registrarTipoValor(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoValorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void actualizarTipoValor(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoValorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void eliminarTipoValor(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoValorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaTipoValorTO consultarTipoValor(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosTipoValorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.PaginacionTO consultarTotalTipoValor(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosTipoValorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO registrarCaracterisitica(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO actualizarCaracteristica(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO eliminarCaracteristica(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO[] consultarCaracteristicas(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CaracteristicaTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO registrarAgrupador(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO eliminarAgrupador(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaAgrupadorTO consultarAgrupadores(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosAgrupadorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO consultarDetalleAgrupador(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaTipoCarteraTO consultarTipoCartera(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosTipoCarteraTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaCatalogosTO consultarTiposCaracteristica() throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaCatalogosTO consultarTiposPersona() throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaCatalogosTO consultarTiposOperacion() throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaCatalogosTO consultarUnidadesTiempo(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.UnidadTiempoTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaCatalogosTO consultarTiposOperador() throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ResultadoConsultaCatalogosTO consultarEstados() throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO actualizarAgrupador(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.AgrupadorTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void eliminarSubGrupo(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.SubGrupoTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.SubGrupoTO actualizarSubGrupo(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.SubGrupoTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void registrarParametroSistema(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ParametroSistemaTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void registrarContrato(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ContratoTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.UsuarioTO registrarUsuario(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.UsuarioTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public void registrarRecordatorio(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.RecordatorioTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.SubGrupoTO[] consultarSubgruposPorTipoValor(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.CriteriosSubGrupoTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ModuloTO registrarModulo(mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.ModuloTO arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoMercadoTO[] consultarTipoMercados() throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public boolean existenciaTipoValor(java.lang.String arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
    public mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.TipoValorTO consultaXIdTV(java.lang.String arg0) throws java.rmi.RemoteException, mx.com.actinver.negocio.bursanet.practicasventa.ws.catalogos.Exception;
}
